// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF7l8N0UDOGOqZmRdBJXroqzK-Xh9mbz8',
    appId: '1:344723325741:web:8a07f9aa8b792b856389a4',
    messagingSenderId: '344723325741',
    projectId: 'aryan-4a8b4',
    authDomain: 'aryan-4a8b4.firebaseapp.com',
    storageBucket: 'aryan-4a8b4.firebasestorage.app',
    measurementId: 'G-VSHDD7G33P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAD-NHGpKYACtVF0y2rbU33YwMzueNiYQ',
    appId: '1:344723325741:android:5f4df30a5c18e3126389a4',
    messagingSenderId: '344723325741',
    projectId: 'aryan-4a8b4',
    storageBucket: 'aryan-4a8b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUQ3zxXEUrL-eL8RgBfltctTiFOZqyNA',
    appId: '1:344723325741:ios:b27dda58630cab266389a4',
    messagingSenderId: '344723325741',
    projectId: 'aryan-4a8b4',
    storageBucket: 'aryan-4a8b4.firebasestorage.app',
    iosBundleId: 'com.example.fixbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtUQ3zxXEUrL-eL8RgBfltctTiFOZqyNA',
    appId: '1:344723325741:ios:b27dda58630cab266389a4',
    messagingSenderId: '344723325741',
    projectId: 'aryan-4a8b4',
    storageBucket: 'aryan-4a8b4.firebasestorage.app',
    iosBundleId: 'com.example.fixbit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF7l8N0UDOGOqZmRdBJXroqzK-Xh9mbz8',
    appId: '1:344723325741:web:134c8b16258ed4ca6389a4',
    messagingSenderId: '344723325741',
    projectId: 'aryan-4a8b4',
    authDomain: 'aryan-4a8b4.firebaseapp.com',
    storageBucket: 'aryan-4a8b4.firebasestorage.app',
    measurementId: 'G-DC0EJHYRTE',
  );
}